extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_castle_wall_lights;
extern Lights1 castle_grounds_dl_f3dlite_material_lights;
extern Lights1 castle_grounds_dl_ground_lights;
extern Lights1 castle_grounds_dl_grass_lights;
extern u8 castle_grounds_dl_bob_textures_01000_rgba16_blue_ci8[];
extern u8 castle_grounds_dl_bob_textures_01000_rgba16_blue_ci8_pal_rgba16[];
extern u8 castle_grounds_dl_castle_grounds_textures_08000_rgba16_ci8[];
extern u8 castle_grounds_dl_castle_grounds_textures_08000_rgba16_ci8_pal_rgba16[];
extern u8 castle_grounds_dl_castle_grounds_textures_03800_rgba16_ci8[];
extern u8 castle_grounds_dl_castle_grounds_textures_03800_rgba16_ci8_pal_rgba16[];
extern Vtx castle_grounds_dl_Castle_mesh_layer_1_vtx_0[115];
extern Gfx castle_grounds_dl_Castle_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Castle_mesh_layer_1_vtx_1[32];
extern Gfx castle_grounds_dl_Castle_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Ground_mesh_layer_1_vtx_0[65];
extern Gfx castle_grounds_dl_Ground_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Ground_mesh_layer_1_vtx_1[490];
extern Gfx castle_grounds_dl_Ground_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Suzanne_mesh_layer_1_vtx_0[1066];
extern Gfx castle_grounds_dl_Suzanne_mesh_layer_1_tri_0[];
extern Gfx mat_castle_grounds_dl_castle_wall[];
extern Gfx mat_revert_castle_grounds_dl_castle_wall[];
extern Gfx mat_castle_grounds_dl_f3dlite_material[];
extern Gfx mat_castle_grounds_dl_ground[];
extern Gfx mat_revert_castle_grounds_dl_ground[];
extern Gfx mat_castle_grounds_dl_grass[];
extern Gfx mat_revert_castle_grounds_dl_grass[];
extern Gfx castle_grounds_dl_Castle_mesh_layer_1[];
extern Gfx castle_grounds_dl_Ground_mesh_layer_1[];
extern Gfx castle_grounds_dl_Suzanne_mesh_layer_1[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
